import type { SolanaWestFaqExpandedItem } from "./solana-west-faq-expanded.types";
import expanded from "./solana-west-faq-expanded.items.json";

/** 100 FAQs — grouped by section; mirrors `solana-west-faq-expanded.items.json` (generated by `scripts/gen-solana-faq-expanded.mjs`). */
export const SOLANA_WEST_FAQ_EXPANDED_ITEMS = expanded as readonly SolanaWestFaqExpandedItem[];
